image: node:10.15.3
pipelines:
  branches:
    develop:
      - step:
          name: Installing & Build
          deployment: develop
          caches:
            - node
          script:
            - npm install
            - export REACT_APP_AUTH_KEY=$REACT_APP_AUTH_KEY
            - export REACT_APP_API_URL=$REACT_APP_API_URL
            - export REACT_APP_SENTRY_DSN=$REACT_APP_SENTRY_DSN
            - export REACT_APP_ENVIRONMENT=$REACT_APP_ENVIRONMENT
            - npm run build:dev
          artifacts:
            - build/build_dev/**
      - step:
          name: Deploy to S3
          script:
            - pipe: atlassian/aws-s3-deploy:1.1.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: visitor.dev.42seoul.io
                ACL: 'public-read'
                LOCAL_PATH: 'build/build_dev'
      - step:
          name: Invalidate Cloudfront Cache
          script:
            - pipe: atlassian/aws-cloudfront-invalidate:0.6.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                DISTRIBUTION_ID: E1L4G60KO39N9F
    main:
      - step:
          name: Installing & Build
          deployment: production
          caches:
            - node
          script:
            - npm install
            - export REACT_APP_AUTH_KEY=$REACT_APP_AUTH_KEY
            - export REACT_APP_API_URL=$REACT_APP_API_URL
            - export REACT_APP_SENTRY_DSN=$REACT_APP_SENTRY_DSN
            - export REACT_APP_ENVIRONMENT=$REACT_APP_ENVIRONMENT
            - npm run build:prod
          artifacts:
            - build/build_prod/**
      - step:
          name: Deploy to S3
          trigger: manual
          script:
            - pipe: atlassian/aws-s3-deploy:1.1.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: visitor.42seoul.io
                ACL: 'public-read'
                LOCAL_PATH: 'build/build_prod'
      - step:
          name: Invalidate Cloudfront Cache
          trigger: manual
          script:
            - pipe: atlassian/aws-cloudfront-invalidate:0.6.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                DISTRIBUTION_ID: E74D246JN9MJT
